# Generated by Django 4.2.3 on 2023-07-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentplan",
            name="minimum_deposit",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="Gender",
            field=models.CharField(choices=0, default="M", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(default="Nigeria", max_length=200),
            preserve_default=False,
        ),
    ]
