# Generated by Django 4.2.3 on 2023-07-28 08:14

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_investmentplan_minimum_deposit_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
