# Generated by Django 4.2.3 on 2023-07-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_user_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="Gender",
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="Male", max_length=10
            ),
            preserve_default=False,
        ),
    ]
