# Generated by Django 4.2.3 on 2023-08-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_payments_deposit_completion_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="completion_percentage",
            field=models.IntegerField(default=0),
        ),
    ]
