# Generated by Django 4.2.3 on 2023-08-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_deposit_status_alter_withdrawal_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deposit",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="investmentplan",
            options={"ordering": ["minimum_deposit"]},
        ),
        migrations.AlterModelOptions(
            name="payments",
            options={"ordering": ["payment_type"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["balance"]},
        ),
        migrations.AlterModelOptions(
            name="withdrawal",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="deposit",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="minimum_deposit",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
